site_name: Jekyll Example
github_url: "https://github.com/pconrad-webapps/pconrad-webapps.github.io"

exclude: [vendor]

timezone: America/Los_Angeles

collections:
  topics:
    output: true
    permalink: /topics/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: topics
    values:
      layout: default


